### ISSUE TITLE
Meta Tag - Keywords - Update

### ISSUE THREAD

**Issue by tborba1** [wtm-modesto/iwd23#12]
index.html
- [x] Include updated names for hosts, featured speakers, and special guests.
- [x] Include MJC and Modesto Junior College

speakers.html
- [x] Include updated names for hosts, featured speakers, and special guests.
- [x] Include MJC and Modesto Junior College

**Comment by tborba1** [comment]
b253de5638a486f67873fef53cf147f4b0f58599

**Comment by tborba1** [comment]
206ed994b008aaadccee5b8a1864d9ac34b866e8
